fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    vcsrepo: https://github.com/puppetlabs/puppetlabs-vcsrepo
    inifile: https://github.com/puppetlabs/puppetlabs-inifile
  symlinks:
    nagdash: "#{source_dir}"
