name 'opentable/nagdash'
version '0.1.0'
author 'opentable'
license 'MIT'
summary 'Module that will install the Nagdash dashboard on a webserver'
project_page 'https://github.com/opentable/puppet-nagdasht'
dependency    'puppetlabs/stdlib', '>=3.0.0'
dependency    'puppetlabs/vcsrepo', '>=0.1.2'